version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI
      - "4317:4317" # the open telemetry grpc port for sending traces
      - "4318:4318" # the open telemetry grpc port for sending traces
    environment:
      - COLLECTOR_OTLP_ENABLED=true